mindmap
  root((Apprenant))
    Dit
      Dit["« J'aimerais comprendre pourquoi ma compétence n'est pas validée et comment m'améliorer. »"]
      Dit["« Les commentaires des formateurs m'aident à savoir ce que je dois travailler. »"]

    Fait
      Fait["Consulte ses compétences validées et lit les commentaires des formateurs pour s’améliorer."]
      Fait["Demande des clarifications s'il ne comprend pas un feedback."]
    Ressent
      Ressent["Parfois confus par les évaluations, il souhaite avoir plus de clarté sur ses points forts et ses axes d’amélioration."]
      Ressent["Motivé lorsqu’il reçoit des commentaires constructifs qui l’aident à progresser.."]
    Besoin
      Besoin["Un espace clair pour voir ses compétences validées et lire les retours de ses formateurs."]
      Besoin["Des commentaires précis qui l’aident à comprendre comment atteindre le niveau suivant."]
