mindmap
  root((Responsable
            de
        Formation))
    Dit
      Dit["<< Je dois m'assurer que les évaluations sont précises pour chaque compétence. >>"]
      Dit["<< Les compétences doivent être validées de manière cohérente pour toutes les formations. >>"]

    Fait
      Fait["Supervise les processus d'évaluation et de validation des compétences pour garantir la qualité des formations."]
      Fait["Analyse les commentaires et les niveaux de compétence pour vérifier leur alignement avec les standards de la filière."]
    Ressent
      Ressent["Inquiet de la cohérence des évaluations entre les formateurs."]
      Ressent["Cherche à maintenir un niveau de compétence élevé et standardisé."]
    Besoin
      Besoin["Un outil clair pour visualiser les compétences validées, avec des commentaires détaillés pour chaque évaluation."]
      Besoin["Un suivi précis pour garantir l’homogénéité des validations."]
