@startuml
left to right direction

actor Trainer

rectangle pkg_validation {
  usecase "Evaluate Learner's Skill" as U1
  usecase "Assign Skill Level" as U2
  usecase "Provide Feedback" as U3
}

Trainer -- U1
U1 <.. U2 : <<extend>>
U1 <.. U3 : <<extend>>

@enduml
